spring:
  application:
    name: UrlShortener

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://localhost:3308/shortener_db}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:Hop2005@}
