server:
  port: 8080

spring:
  application:
    name: UrlShortener

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://localhost:3308/shortener_db}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:Hop2005@}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: Hop2005@
      timeout: 2000

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:147.93.29.117:9092,147.93.29.117:9093}