version: '3.9'

services:
  shortener-mysql:
    container_name: shortener-mysql
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Hop2005@
      MYSQL_DATABASE: shortener_db
    ports:
      - "3308:3306"
    volumes:
      - shortener-mysql-data:/var/lib/mysql
    networks:
      - shortener-network

  shortener-redis:
    container_name: shortener-redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - shortener-redis-data:/data
    networks:
      - shortener-network

volumes:
  shortener-mysql-data:
  shortener-redis-data:

networks:
  shortener-network:
    driver: bridge

# docker compose up -d shortener-mysql