name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    services:
      shortener-mysql:
        image: mysql:8.2.0
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        env:
          MYSQL_ROOT_PASSWORD: Hop2005@
          MYSQL_DATABASE: shortener_db
        ports:
          - 3308:3306

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Wait for MySQL to be ready
        run: |
          while ! mysqladmin ping -h"127.0.0.1" --port=3308 --silent; do
            echo "Waiting for database connection..."
            sleep 2
          done

      - name: Set environment variables
        run: echo "Setting environment variables"
        env:
          MYSQL_URL: "jdbc:mysql://127.0.0.1:3308/shortener_db"
          MYSQL_USERNAME: "root"
          MYSQL_PASSWORD: "Hop2005@"

      - name: Run tests
        run: ./gradlew test --no-daemon

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4